### ISSUE TITLE
Upgraded to v2 and plugin not starting

### ISSUE THREAD

**Issue by mgf909** [pbegg/signalk-to-influxdb-v2-buffering#11]
HI,
ive just upgraded from the v1 version to the latest, however the plugin wont start:
`
May 23 14:21:05 2021-05-23T04:21:05.492Z signalk-to-influxdb-v2-buffering Signalk To Influxdbv2.0 Started...
May 23 14:21:05 error starting plugin: TypeError: Cannot read property 'forEach' of undefined
May 23 14:21:05 TypeError: Cannot read property 'forEach' of undefined at Object._start [as start] (/home/pi/.signalk/node_modules/signalk-to-influxdb-v2-buffering/index.js:124:25) at doPluginStart (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:265:20) at doRegisterPlugin (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:388:13) at registerPlugin (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:219:13) at /usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:170:13 at Array.forEach (<anonymous>) at startPlugins (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:169:63) at Object.start (/usr/local/lib/node_modules/signalk-server/lib/interfaces/plugins.js:55:13) at /usr/local/lib/node_modules/signalk-server/lib/index.js:363:70 at /usr/local/lib/node_modules/signalk-server/node_modules/lodash/lodash.js:4967:15 at Function.forIn (/usr/local/lib/node_modules/signalk-server/node_modules/lodash/lodash.js:13018:11) at startInterfaces (/usr/local/lib/node_modules/signalk-server/lib/index.js:353:7) at /usr/local/lib/node_modules/signalk-server/lib/index.js:273:13 at createServer (/usr/local/lib/node_modules/signalk-server/lib/index.js:317:5) at /usr/local/lib/node_modules/signalk-server/lib/index.js:262:9 at new Promise (<anonymous>)
May 23 14:21:05 (node:22008) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
May 23 14:21:05 signalk-server running at 0.0.0.0:[object Object]
May 23 14:21:06 23 May 14:21:06 - [info] Welcome to Node-RED ===================
May 23 14:21:06 23 May 14:21:06 - [info] Node-RED version: v1.2.9
May 23 14:21:06 23 May 14:21:06 - [info] Node.js version: v12.22.0
May 23 14:21:06 23 May 14:21:06 - [info] Linux 5.10.17-v7l+ arm LE
May 23 14:21:06 GET /admin/ 304 16.263 ms - -`

Ive uninstalled and deleted my old config file and tried using some "default" settings, expecting it to error on not being able to connect/login, but at least getting the plugin to start.,...but this hasnt helped.

Any ideas what may be the issue?

This is the config generated by the new plugin ( token and org modified ):

`{
  "configuration": {
    "influxHost": "https://us-west-2-1.aws.cloud2.influxdata.com",
    "influxToken": "9g_EjbJVfJH4wPO1qcyt9WnPWMhCadsasdasdUODvCubBXGtqDdcmPd-KzyNz2AYtqQNKpps_2imiQ6lM5g==",
    "influxOrg": "theldaass",
    "influxBucket": "signalk2",
    "writeOptions": {
      "batchSize": 1000,
      "flushInterval": 30000,
      "maxBufferLines": 32000,
      "maxRetries": 3,
      "maxRetryDelay": 5000,
      "minRetryDelay": 180000,
      "retryJitter": 200
    },
    "pathArray": [
      {
        "path": "environment.*",
        "interval": 1000
      }
    ]
  },
  "enabled": true
}`

**Comment by mgf909** [comment]
Like to add there is no longer a field to set the path for the files to be stored??

![image](https://user-images.githubusercontent.com/6590153/119248356-f5b97e00-bbd3-11eb-9913-d27f9b858e8b.png)

**Comment by mgf909** [comment]
Ah.... if I add a Tag "boat" value "blah" - it loads....

Can you advise some examples of what tags to use? im familiar with their use in Influx  but not sure what tags pairs would be good to have for this plugin?

**Comment by pbegg** [comment]
If you wanted to compare multiple boats on the one database I use the tag:value 'vesselname':'testvessel'

Then when viewing influx data you can filter by this tag value.

I should change the plugin so this is not required if the end user doesn't require it

**Comment by mgf909** [comment]
All good - Thanks again.
