### ISSUE TITLE
Not uploading data to influxdb cloud bucket

### ISSUE THREAD

**Issue by glover-glitch** [pbegg/signalk-to-influxdb-v2-buffering#12]
Hello.

I have followed the read.me but I seem to be having a problem.
None of my data appears to be uploading to my bucket in influxdb-cloud.
I have verified that I used the correct influxdb-cloud settings in this plugin.

Please see the attached screenshot.
I assumed that all tags would be sent by default.
Do I have to specify each tag that I want to be uploaded?
If so, what is the correct syntax?
I apologize for my confusion, the read.me was a little bit unclear to me.  

Thank you.

![image](https://user-images.githubusercontent.com/73205151/119268691-b8e08d80-bbb9-11eb-9f7b-2d07287d23c4.png)

**Comment by pbegg** [comment]
Sorry for the readme, it needs updating.
For paths you can enter "*" without the quotes and select a frequency.

You also currently need to enter a default tag and value.

**Comment by glover-glitch** [comment]
Perfect!  
I am now sending my boats signalk data to the influxdb-cloud.

Thank you so much!
