### ISSUE TITLE
What happens when two devices send data to the same device instance?

### ISSUE THREAD

**Issue by glover-glitch** [pbegg/signalk-to-influxdb-v2-buffering#14]
Hello!

I have to say that I am really enjoying this module.
It works great!

But.. I have run across a small problem that I am hoping you can resolve or provide some guidance on.
While I was monitoring electrical.batteries.1.voltage, Influx and grafana would flip between the correct voltage and a value of 0.
It appeared to be random.

Tracking down that issue brought me face to face with the following scenario;
Multiple battery monitors on the boat are sending data to the same device address. In this case 'electrical.batteries.1.voltage'. (and electrical.batteries.0.voltage)

This module can't see the difference between them and is sending either value to influxdb.  It appears to choose at random.
(As an aside for reference, Willhelmsk resolves this issue by allowing me to choose which data source to pull the value from. i.e. Canbus 1 or Canbus 224)

Is there anyway to have this module choose which data source to pull data from as well?
Or to send both values to influx and we can choose there?

![image](https://user-images.githubusercontent.com/73205151/120016442-3afdf700-bfaa-11eb-8ddd-3e47679b67b3.png)

**Comment by pbegg** [comment]
As A quick fix you could use source priorities in the data connections tab.
Otherwise i think we would need to do the same as signalk-to-influx and include a tag name 'source' value of the source name.

**Comment by glover-glitch** [comment]
Perfect, Thank you!

Your 'quick fix' worked like a charm.
It is sufficient for my needs.

Thanks for being so supportive and having a very quick response time. 
Have great weekend!

![image](https://user-images.githubusercontent.com/73205151/120072678-a901f700-c05a-11eb-97c7-663f7182aae4.png)

**Comment by pbegg** [comment]
No dramas! Glad it's of use
