### ISSUE TITLE
Not writing

### ISSUE THREAD

**Issue by BECSgmbh** [pbegg/signalk-to-influxdb-v2-buffering#15]
I have a pi4 with an MCAN Hat. I installe the signalk-to-influxdb-v2-buffering plugin. I have filled in the config according to my knowledge. However, I still have difficulties. Because no data is written in the buffer and on the server. Can you make an example how to describe the config values default tags correctly.

Thanks for the help

**Comment by pbegg** [comment]
Can you please send me a copy of the config settings to ensure it is setup correctly

**Comment by BECSgmbh** [comment]
Thank you for answer and i hope you can help me. 
![Influx1](https://user-images.githubusercontent.com/85371361/120886708-986bf680-c5ef-11eb-941e-4aa468dbf0e2.png)
![DefaultTag](https://user-images.githubusercontent.com/85371361/120886712-9ace5080-c5ef-11eb-8de4-fb11573b0a76.png)

**Comment by pbegg** [comment]
Change default tags to something like:
Tag name: vessel
Tag value: my vesselname

Paths:
Signalk path to record:
propulsion.port.runTime
Record interval:
1000

**Comment by BECSgmbh** [comment]
Thank you for the help now it works. great
