### ISSUE TITLE
plans to support environment, navigation and tanks?

### ISSUE THREAD

**Issue by virtuvas** [pbegg/signalk-to-influxdb-v2-buffering#2]
hello,

still in the setup process of getting lots of NMEA2000 (mainly) data from my boat to my work server (and then visualise via grafana)
Since 10m out of 12 boat is in it's mooring I'm more keen on getting condition and info on the environment and tank data...
OK, navigation is also interesting to keep a better log of where you are especially when there's no data coverage on the way.

so, just a question on what are your plans to support these categories?

cheers

V.

**Comment by pbegg** [comment]
The plugin still currently has a few bugs. When the data is buffered it loses the first 30 seconds, which was not happening on tests I completing. Now with it running on a boat that frequently loses internet connection, there are a few gaps in the data.
To add support for the other paths is not too difficult however thinking further I am leaning towards changing the structure of the app to just record the path value as the measurement name and not break it into measurement tags and fields.
To then visualise on Grafana I can use regexp to filter the data.
This plugin will use quite an amount of bandwidth, you may be better with another solution such as using node red to send through the data you want at the resolution you want. I'm hoping to get some more time to work on this plugin over the next few weeks

**Comment by virtuvas** [comment]
thanks, will see how I'll do it!
