### ISSUE TITLE
errors if bufferdirectory does not exist.

### ISSUE THREAD

**Issue by mgf909** [pbegg/signalk-to-influxdb-v2-buffering#5]
Hi guys - appreciate you creating this plugin. 
Just doing a test setup, and encountered an error..
`Mar 08 20:53:09 2021-03-08T09:53:09.800Z signalk-to-influxdb-v2-buffering Sending 4 metrics to be uploaded to influx
Mar 08 20:53:09 (node:30611) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/pi/signalkbuffer/1615197189894.json' at Object.openSync (fs.js:443:3) at Object.writeFileSync (fs.js:1194:35) at Object.exports.buffer (/home/pi/.signalk/node_modules/signalk-to-influxdb-v2-buffering/buffer.js:9:5) at influxdb.write.then.catch.err (/home/pi/.signalk/node_modules/signalk-to-influxdb-v2-buffering/index.js:47:16) at process._tickCallback (internal/process/next_tick.js:68:7)
Mar 08 20:53:09 (node:30611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)`

error went away after i manually created the directory.... i guess you may want to create this dir on initial config?

**Comment by pbegg** [comment]
I will look to change this in the future - for now we just need to make sure the directory exists.
